language: python
python:
  - "2.7"
install:
  - pip install pylint
  - pip install pep8
  - python setup.py install
script:
  - pep8 --ignore=E501 *.py ec2stack tests
  - pylint --rcfile=pylint.rc *.py ec2stack tests

# Force travis-ci build
