language: python
python:
- '2.7'
install:
- pip install pylint
- pip install pep8
- pip install coverage
- python setup.py install
script:
- pep8 --ignore=E501 *.py ec2stack
- pylint --rcfile=pylint.rc *.py ec2stack
- nosetests --with-coverage --cover-erase --cover-package=ec2stack --cover-html
after_success:
- ls -la
- sh .deploy-coverage.sh
env:
  global:
    secure: dUNHx6q6ziCb7pXr/fb/OZS8fyB14RF8/rEEggBEzgn2L7KM78LVFyFNmW+QZ7lvJpZ806mfjdmvmz0DpR1k6kfokrr6txBzHDMEUebc9RnVnmsoNNWIRLiV/+YzUsVeFixogVz/z06yaycOC8knVExcNfGMfmiBg5PextydXSQ=
